### ISSUE TITLE
Why white noise

### ISSUE THREAD

**Issue by YetiXie1994** [ehabets/INF-Generator#2]
In matlab code, why diffuse noise is generated from "white noise"?

**Comment by ehabets** [comment]
We used white noise for the generation because the objective was to generate temporally white noise signals with a specific spatial coherence. In case a different coloration is desired, you can filter the output signal. If you like to generate non-stationary diffuse noise signals, I would recommend you to have a look at [this](https://github.com/ehabets/ANF-Generator).
